plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.ruroad.karta'
    compileSdk 34
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "ru.ruroad.karta"
        minSdk 24
        targetSdk 34
        versionCode 4
        versionName "1.2"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
